global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # AirChainPay Relay Server
  - job_name: 'airchainpay-relay'
    static_configs:
      - targets: ['localhost:4000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Node.js Application Metrics
  - job_name: 'nodejs'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Docker Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 15s

  # Health Checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['localhost:4000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

# Recording Rules
rule_files:
  - "recording_rules.yml" 