version: '3.8'

services:
  relay-staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airchainpay-relay-staging
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=staging
      - DEBUG=false
    env_file:
      - .env.staging
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["node", "src/server.js"] 