version: '3.8'

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airchainpay-relay
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./data:/usr/src/app/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 