global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@airchainpay.com'
  smtp_auth_username: 'alerts@airchainpay.com'
  smtp_auth_password: 'YOUR_SMTP_PASSWORD'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'pager-duty-critical'
      continue: true
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 1h

    # Security alerts - immediate notification
    - match:
        alertname: UnauthorizedAccessAttempts
      receiver: 'security-team'
      continue: true
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 30m

    # BLE alerts - notify operations team
    - match:
        alertname: BLEDeviceConnectionIssues
      receiver: 'operations-team'
      continue: true

    # Transaction processing alerts
    - match:
        alertname: HighTransactionFailureRate
      receiver: 'development-team'
      continue: true

    # System resource alerts
    - match:
        alertname: HighCPUUsage
      receiver: 'operations-team'
      continue: true

    - match:
        alertname: HighMemoryUsage
      receiver: 'operations-team'
      continue: true

    - match:
        alertname: DiskSpaceLow
      receiver: 'operations-team'
      continue: true

inhibit_rules:
  # Inhibit critical alerts when server is down
  - source_match:
      alertname: RelayServerDown
    target_match:
      severity: critical
    equal: ['service']

  # Inhibit resource alerts when server is down
  - source_match:
      alertname: RelayServerDown
    target_match:
      alertname: HighCPUUsage
    equal: ['instance']

  - source_match:
      alertname: RelayServerDown
    target_match:
      alertname: HighMemoryUsage
    equal: ['instance']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#airchainpay-alerts'
        send_resolved: true
        title: '{{ template "slack.airchainpay.title" . }}'
        text: '{{ template "slack.airchainpay.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.airchainpay.grafana" . }}'

  - name: 'pager-duty-critical'
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        send_resolved: true
        description: '{{ template "pagerduty.airchainpay.description" . }}'
        severity: '{{ if eq .GroupLabels.severity "critical" }}critical{{ else }}warning{{ end }}'

  - name: 'security-team'
    slack_configs:
      - channel: '#airchainpay-security'
        send_resolved: true
        title: '🚨 Security Alert: {{ .GroupLabels.alertname }}'
        text: '{{ template "slack.security.text" . }}'
    email_configs:
      - to: 'security@airchainpay.com'
        send_resolved: true
        subject: 'Security Alert: {{ .GroupLabels.alertname }}'

  - name: 'operations-team'
    slack_configs:
      - channel: '#airchainpay-ops'
        send_resolved: true
        title: '🔧 Operations Alert: {{ .GroupLabels.alertname }}'
        text: '{{ template "slack.ops.text" . }}'
    email_configs:
      - to: 'ops@airchainpay.com'
        send_resolved: true
        subject: 'Operations Alert: {{ .GroupLabels.alertname }}'

  - name: 'development-team'
    slack_configs:
      - channel: '#airchainpay-dev'
        send_resolved: true
        title: '💻 Development Alert: {{ .GroupLabels.alertname }}'
        text: '{{ template "slack.dev.text" . }}'
    email_configs:
      - to: 'dev@airchainpay.com'
        send_resolved: true
        subject: 'Development Alert: {{ .GroupLabels.alertname }}'

templates:
  - '/etc/alertmanager/template/*.tmpl' 